#!/bin/sh

mkdir -p {{pkg.svc_var_path}}/logs
mkdir -p {{pkg.svc_var_path}}/data
mkdir -p {{pkg.svc_var_path}}/commitlog
mkdir -p {{pkg.svc_var_path}}/saved_caches
mkdir -p {{pkg.svc_var_path}}/hints
mkdir -p {{pkg.svc_config_path}}/triggers


{{~#if cfg.commitlog.mount}}
if [ ! -d "{{pkg.svc_var_path}}/commitlog" ]; then
  if ! mountpoint "{{cfg.commitlog.mount}}"; then
    echo "You must provide a mount point Cassandra commitlog and bind it to 'commitlog.mount' in order to start Cassandra"
    exit 1
  fi
fi
{{~/if}}
